---
development:
  cloud_name: daryatoys
  api_key: '995396864439711'
  api_secret: ZtPNK13Ioaa6jDCejz9siYJ28wU
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: daryatoys
  api_key: '995396864439711'
  api_secret: ZtPNK13Ioaa6jDCejz9siYJ28wU
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: daryatoys
  api_key: '995396864439711'
  api_secret: ZtPNK13Ioaa6jDCejz9siYJ28wU
  enhance_image_tag: true
  static_image_support: false
